export * from './client';
export * as authApi from './auth';
export * as salesApi from './sales';
export * as dashboardApi from './dashboard';
export * as profileApi from './profile';
export * as teamApi from './team';
export * as ratesApi from './rates';
export * as allocationsApi from './allocations';
export * as payrollApi from './payroll';
export * as paystubsApi from './paystubs';
export * as goalsApi from './goals';
export * as announcementsApi from './announcements';
export * as ticketsApi from './tickets';
export * as adminApi from './admin';
